[project]
name = "multi-hop-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.8.0.post1",
    "flagembedding>=1.3.5",
    "google-generativeai>=0.8.6",
    "python-dotenv>=1.2.1",
]
